Feature/task opt in and opt out
algorandfoundation/algokit-utils-ts pull request #148
Opened 2023-10-11 03:17 UTC by negar-abbasi

## Proposed Changes

- opt in to a single asset
- opt out on multiple assets, grouped into a single transaction 
-

2023-10-12 00:37 UTC, negar-abbasi commented on src/asset.ts
> +  await transferAsset(
It is not hard but the user story is for only one asset to be opted in and a number of assets to be opted out.

2023-10-13 11:06 UTC, aorumbayev requested changes
@negar-abbasi please also pull latest from main branch as well as its out of sync by a good # of commits

2023-10-13 11:06 UTC, aorumbayev commented on src/asset.ts
> +async function ensureAccountIsValid(client: algosdk.Algodv2, account: algosdk.Account) {
Same comment as in `py` version, are these meant to be used only by optin and optout or we want to export them? If we aren't exporting them ensure you are only exposing the optIn and optOut to users

2023-10-13 11:06 UTC, aorumbayev commented on src/asset.ts
> +async function ensureAssetFirstOptIn(client: algosdk.Algodv2, account: algosdk.Account, assetIds: number[]) {
Same comment as in `py` version, are these meant to be used only by optin and optout or we want to export them? If we aren't exporting them ensure you are only exposing the optIn and optOut to users

2023-10-13 11:06 UTC, aorumbayev commented on src/asset.ts
> +export async function optOut(client: Algodv2, optoutAccount: Account, assetIds: number[]): Promise<Record<number, string>> {
in py version you named the account field as `account`, lets either rename it to account here or rename it to match the current title here on py version for consistency

2023-10-13 11:06 UTC, aorumbayev commented on src/asset.ts
> +export async function optOut(client: Algodv2, optoutAccount: Account, assetIds: number[]): Promise<Record<number, string>> {
```suggestion
/**
 * Opt out of multiple assets in Algorand blockchain.
 *
 * @param {Algodv2} client - An instance of the Algodv2 client used to interact with the Algorand blockchain.
 * @param {Account} optoutAccount - The Algorand account that wants to opt out of the assets.
 * @param {number[]} assetIds - An array of asset IDs representing the assets to opt out of.
 * @returns {Promise<Record<number, string>>} - A record object containing asset IDs as keys and their corresponding transaction IDs as values.
 */
export async function optOut(client: Algodv2, optoutAccount: Account, assetIds: number[]): Promise<Record<number, string>> {
```

2023-10-13 11:06 UTC, aorumbayev commented on src/asset.ts
> +export async function optIn(client: Algodv2, optInAccount: Account, assetIds: number[]) {
```suggestion
/**
 * Opt in to a list of assets on the Algorand blockchain.
 *
 * @param client - An instance of the Algodv2 class from the `algosdk` library.
 * @param optInAccount - An instance of the Account class from the `algosdk` library representing the account that wants to opt in to the assets.
 * @param assetIds - An array of asset IDs that the account wants to opt in to.
 * @returns A record object where the keys are the asset IDs and the values are the corresponding transaction IDs for successful opt-ins.
 * @throws If there is an error during the opt-in process.
 */
export async function optIn(client: Algodv2, optInAccount: Account, assetIds: number[]) {
```

2023-10-17 15:25 UTC, aorumbayev requested changes

2023-10-17 15:25 UTC, aorumbayev commented on src/asset.ts
> +async function ensureAssetFirstOptIn(client: algosdk.Algodv2, account: algosdk.Account, assetIds: number[]) {
This method and the one below are redundant, both are almost identical except for min balance parameters, you can combine them into a single method called ensureAssetBalance and take a third param of custom enum type call ValidationType (with option OptIn or OptOut), based on this enum you can them figure out whether to check if balance is >= 0 (opted in) or asset should not be inside accountInfo response at all (opted out)

2023-10-18 13:40 UTC, aorumbayev approved these changes

2023-10-18 13:42 UTC, merged